### ISSUE TITLE
"JSX/ES2015" React transpiling

### ISSUE THREAD

**Issue by osman-masood** [QQuick/Transcrypt#121]
Just an idea. What if we could do JSX-like and ES2015 class syntax? Something like:

``` python
class HelloComponent(React.Component):
    def __init__(self, **props):
        self.state = {'counter': 0}
        self.props = props

    def updateCounter(self):
        self.state['counter'] += 1

    def componentDidMount(self):
        setInterval(self.updateCounter, 1000)

    def render(self):
        return div({'className': 'maindiv'},
                   h1('Hello', self.props['name']),
                   p('Lorem ipsum dolor sit ame.'),
                   p('Counter: ', self.state['counter'])
                   )
```

The goal here would be to write clean React code in Python. 

A "step 2" would be to stub out `React` and its classes, as well as the supported HTML tags (`p` `h1` etc), then we'll gain the benefits of autocompletion and some type inference, too.

**Comment by JdeH** [comment]
Hi Oman,

Thanks for the feedback.
I am not a React expert, so I'll first have to do some homework studying...
Will get back on this.

Kind regards
Jacques de Hooge

**Comment by AXGKl** [comment]
@osman-masood : To prepare for a [talk](https://www.pymunich.com/) I'm doing soon (subject: Transcrypt / Redux / FRP: Reactive Isomorphic Web Components In Python Only)

My question to you, referring to *What if we could do JSX-like and ES2015 class syntax? *
What do you actually miss, in my opinion this *is* already possible in Transcrypt?

**Comment by osman-masood** [comment]
@AXGKl I tried several ways of getting it to work, but keep getting errors. For example the above code produces `react_demo.js:87 Uncaught TypeError: cls.__new__ is not a function`.

Try this commit made on my fork: https://github.com/osman-masood/Transcrypt/commit/f75d1df4b56b2c06560b3f624b8f3004d01639ee

Still looking into this...

**Comment by AXGKl** [comment]
@osman-masood : Ok understood, so its really a bug somewhere in the react demo or your code. Would love to look into this deeper but unfortunately these days some project delivery ...minutes are running out :-/
Zero use to you for now, but in general I must say that I found react always a bit too loaded, API wise. Was having more fun with riotjs for reactive components. Meanwhile I don't even use this anymore but pure transcrypt only, together with a templating engine.

**Comment by fdv1** [comment]
Hi,

Thanks for this awesome project! I just started using it and stumble exactly on the same issue... I would love to help but my JS is kind of non existent.
cheers,
Francois

**Comment by JdeH** [comment]
This issue "hangs". @osman-masood and @fdv1 I can't help you since I've not enough knowledge of react. Does any of this require an extension or modification Transcrypt itself? If so, which modification exactly. Or does it require someone to make a library for it, e.g. to replace the use of JSX? If so can any of you do that?

**Comment by JdeH** [comment]
I'll close this for now, since it seems to linger.
If anyone starts working on this, feel free to reopen.

**Comment by osman-masood** [comment]
@JdeH I was working on a "transpiler" from JSX to JS, which would work separately from Transcrypt (at least initially), but never finished.

**Comment by JdeH** [comment]
That happens...
So I guess it's ok this issue is closed now?
Hope you keep on using Transcrypt, though...

Kind regards
Jacques

**Comment by osman-masood** [comment]
@JdeH Yep! Closed makes sense for now. Thanks.

**Comment by fdv1** [comment]
Thank you very much. 
I must say that I have been coding in JS since then (I needed to learn it anyway). 
I'll give another go soon...
cheers,Francois

**Comment by dhowland** [comment]
@AXGKl Sorry to resurrect this dead thread, but "Transcrypt / Redux / FRP: Reactive Isomorphic Web Components In Python Only" sounds really interesting.  Is there a video of this talk anywhere?

**Comment by JdeH** [comment]
Hi,

Unfortunately to my knowledge it wasn't video'ed. (@AXGK: right?)
But the slides are available at:

https://axiros.github.io/transcrypt/#/

Hope they contain enough info.

Kind regards
Jacques
